[custom]
;解决DNS泄露，无分流群组
# drop DNS leakage from domestic ip checkers
# support dialer from proxy providers
# WIKI of dialer: https://wiki.metacubex.one/config/proxies/dialer-proxy/
# WIKI of proxy-providers: https://wiki.metacubex.one/config/proxy-providers/


ruleset=节点选择,https://raw.githubusercontent.com/YaoYinYing/AnyRelay/main/rules/masquerade.list
ruleset=节点选择,https://raw.githubusercontent.com/YaoYinYing/AnyRelay/main/rules/ip_sensitive.list

ruleset=谷歌学术,https://raw.githubusercontent.com/YaoYinYing/AnyRelay/main/rules/google_scholar.list
ruleset=DIRECT,https://raw.githubusercontent.com/YaoYinYing/AnyRelay/main/rules/force_direct.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list

ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=DIRECT,[]GEOIP,CN,no-resolve

ruleset=流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list

ruleset=流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list


ruleset=内网应用,https://raw.githubusercontent.com/YaoYinYing/AnyRelay/main/rules/japs_internal.list
ruleset=REJECT,https://raw.githubusercontent.com/YaoYinYing/AnyRelay/main/rules/mobile_antifraud.list
ruleset=REJECT,https://raw.githubusercontent.com/YaoYinYing/AnyRelay/main/rules/my_block.list
ruleset=节点选择,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=节点选择,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=节点选择,[]DOMAIN-SUFFIX,probe.icloud.com
ruleset=节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list

ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list

ruleset=流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=节点选择,[]FINAL


## create proxies and providers
# TODO
#### URL parameters (from GET) for dialer group
; use_dialer=true # switch for dialer
; dialer_group_name=dialer # name of dialer group
; apply_dialer_to='awesome|Scholar' # name pattern of target node that the dialer is applying to 

# this produces:

; proxies:
;   - {name: awesome native IPv4, dialer-proxy: dialer, ...}
;   - {name: awesome native IPv6, dialer-proxy: dialer, ...}
;   - {name: awesome native Warp, dialer-proxy: dialer, ...}
;   - {name: Google Scholar 1, dialer-proxy: dialer, ...}


#### URL parameter (from GET) for providers is a url-encoded dict-like structure of the following:
; proxy_providers: [
;   {'name': 'sub-dialer-provider-1', 'type': 'http', 'url': '...'},
;   {'name': 'relay-provider-1', 'type': 'http', 'url': '...'},
; ]

; proxy-providers:
;   sub-dialer-provider-1:
;     type: http
;     url: "..."
;   relay-provider-1:
;     type: http
;     url: "..."

custom_proxy_group=内网应用`select`[]DIRECT`(JUMP|YNNU|CPB|Internal|Home|University)
custom_proxy_group=谷歌学术`select`(Scholar)`[]自动选择`[]REJECT

custom_proxy_group=节点选择`select`[]自动选择`[]DIRECT`^((?!JUMP|YNNU|CPB|Internal|Home|University|Scholar).)*$
custom_proxy_group=自动选择`url-test`^((?!IEPL|JUMP|YNNU|CPB|Internal|Home|University|Scholar).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=流媒体`select`^((?!IEPL|JUMP|YNNU|CPB|Internal|Home|University|Scholar).)*$
custom_proxy_group=故障转移`fallback`^((?!IEPL|JUMP|YNNU|CPB|Internal|Home|University|Scholar).)*$`http://www.gstatic.com/generate_204`300,,50

# TODO
# select providers w/ matched name pattern from provider form dialer to form a manual selection group

# this will form:
;   - name: dialer-select
;     type: select
;     use:
;       - sub-dialer-provider-1
;       - relay-provider-1

custom_proxy_group=dialer-select`select-use`(sub|dialer|relay)

# TODO
# select providers w/ matched name pattern form dialer to form a manual boadbalance group

# this will form:
;   - name: dialer-lb
;     type: load-balance
;     strategy: round-robin
;     url: http://www.gstatic.com/generate_204
;     interval: 6537
;     tolerance: 100
;     use:
;       - sub-dialer-provider-1
;       - relay-provider-1

custom_proxy_group=dialer-lb`load-balance-use`(sub|dialer|relay)`http://www.gstatic.com/generate_204`6537,,100`round-robin

# now combine as the final dialer group, will be applied to the selected nodes, DIRECT is the fallback as no dialer
custom_proxy_group=dialer`select`[]dialer-select`[]dialer-lb`[]DIRECT

enable_rule_generator=true
overwrite_original_rules=true